version: '3'

services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    restart: always
    volumes:
      - /home/printer/samba/data:/mount/data
    command: '-s "share;/mount/data;yes;no;no;printer" -u "printer;printer"'
